version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - app-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - social-app
  server:
    image: server
    build:
      dockerfile: Dockerfile
      context: './server'
    volumes:
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - social-app
    environment:
      - ACCESS_TOKEN_SECRET={ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET={REFRESH_TOKEN_SECRET}
  web:
    stdin_open: true
    image: web
    build:
      dockerfile: Dockerfile
      context: './web'
    volumes:
      - /app/node_modules
    ports:
      - "80:80"
    networks:
      - social-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    
networks:
  social-app:
    driver: bridge

volumes:
  app-pgdata:
    external: true